export enum OtpCodeStatus {
  SENT= "SENT",
  VERIFIED="VERIFIED",
  EXPIRED="EXPIRED",
  IN_PROGRESS="IN_PROGRESS"
}

export enum verificationPurpose {
  LOGIN="LOGIN",
  PHONE_VERIFICATION="PHONE_VERIFICATION",
  EMAIL_VERIFICATION="EMAIL_VERIFICATION",
  SIGNUP="SIGNUP"
}
